- name: Install and configure Elasticsearch cluster
  hosts:
    - es01
    - es02
    - es03
  become: true
  vars:
    elasticsearch_config_file: /etc/elasticsearch/elasticsearch.yml
    node_roles_master_data: ["master", "data"]
    node_roles_master: ["master"]
    node_name_es01: "es01"
    node_name_es02: "es02"
    node_name_es03: "es03"
  tasks:
    - name: Update the server and install dnf-plugins-core package
      become: true
      dnf:
        name: dnf-plugins-core
        state: present
        update_cache: yes


    - name: Update package cache and fix missing dependencies
      become: true
      dnf:
        update_cache: yes
        name: java-11-openjdk-devel
        state: present

    - name: Set JAVA_HOME Environment Variables
      lineinfile:
        path: /etc/environment
        line: 'JAVA_HOME="/usr/lib/jvm/java-11"'
      environment:
        PATH: "{{ ansible_env.PATH }}:/usr/lib/jvm/java-11/bin"

    - name: Reload environment variables
      become: true
      shell: source /etc/environment

    - name: Verify JAVA_HOME environment variable
      command: echo $JAVA_HOME

    - name: Add ElasticSearch GPG key
      become: true
      rpm_key:
        key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        state: present

    - name: Add ElasticSearch repository
      become: true
      dnf:
        name: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.0.0-x86_64.rpm
        state: present
      when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '8'

    - name: Install ElasticSearch 8 on CentOS 8
      yum:
        name: elasticsearch
        state: present

    - name: Generate Elasticsearch configuration file on es01
      template:
        src: elasticsearch.yml.j2
        dest: "{{ elasticsearch_config_file }}"
        owner: elasticsearch
        group: elasticsearch
        mode: '0644'
      delegate_to: es01
      vars:
        node_roles: "{{ node_roles_master_data }}"
        node_name: "{{ node_name_es01 }}"

    - name: Generate Elasticsearch configuration file on es02
      template:
        src: elasticsearch.yml.j2
        dest: "{{ elasticsearch_config_file }}"
        owner: elasticsearch
        group: elasticsearch
        mode: '0644'
      delegate_to: es02
      vars:
        node_roles: "{{ node_roles_master_data }}"
        node_name: "{{ node_name_es02 }}"

    - name: Generate Elasticsearch configuration file on es03
      template:
        src: elasticsearch.yml.j2
        dest: "{{ elasticsearch_config_file }}"
        owner: elasticsearch
        group: elasticsearch
        mode: '0644'
      delegate_to: es03
      vars:
        node_roles: "{{ node_roles_master }}"
        node_name: "{{ node_name_es03 }}"

    - name: Start Elasticsearch service
      systemd:
        name: elasticsearch
        state: started
        enabled: yes
        
    - name: Add Kibana repository
      become: true
      dnf:
        name: https://artifacts.elastic.co/downloads/kibana/kibana-8.0.0-x86_64.rpm
        state: present
      when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '8'
      delegate_to: es01

    - name: Install Kibana on es01
      become: true
      yum:
        name: kibana
        state: present
      delegate_to: es01

    - name: Start and enable Kibana service on es01
      become: true
      systemd:
        name: kibana
        state: started
        enabled: yes
      delegate_to: es01
      
  handlers:
    - name: Restart Elasticsearch service
      service:
        name: elasticsearch
        state: restarted
